CREATE TABLE `scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`conversionRateMultiplier` int,
	`acvNewAdjustment` int,
	`acvUpsellAdjustment` int,
	`sameQuarterAdjustment` int,
	`nextQuarterAdjustment` int,
	`twoQuarterAdjustment` int,
	`totalRevenueChange` int,
	`totalRevenueChangePercent` int,
	`totalOpportunitiesChange` int,
	`totalOpportunitiesChangePercent` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scenarios_id` PRIMARY KEY(`id`)
);
